name: Web deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github
        uses: actions/checkout@v4
      
      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: ketansayal2004/todo-app-web:${{ github.sha }}
      - name: SSh into machine
        run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}"> ~/ssh_key
            chmod 700 ~/ssh_key

            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{secrets.SSH_MACHINE_IP}} << 'EOF'

            docker pull ketansayal2004/todo-app-web:${{github.sha}}
            docker kill user_web || true
            docker rm user_web || true
            docker run -d --network my_network --name user_web -e NEXTAUTH_URL=${{secrets.FRONTEND_URL}} -e DATABASE_URL="postgresql://postgres:mysecret@postgres:5432/postgres" -e NEXT_PUBLIC_BACKEND_URL=${{secrets.BACKEND_URL}} -e BACKEND_URL="http://user_server:3001" -e AUTH_SECRET="This is an example" -e AUTH_GITHUB_ID=${{secrets.AUTH_GITHUB_ID}} -e AUTH_GITHUB_SECRET=${{secrets.AUTH_GITHUB_SECRET}} -p 3000:3000 ketansayal2004/todo-app-web:${{github.sha}}
            EOF

      

    
    
    